# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - listo

on:
  push:
    branches:
      - feature/build-dockerfile
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_9e56ad5a80334d628a223732ef98eb96 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9d338a6f533e4cd7a5cf71e690419356 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9e56ad5a80334d628a223732ef98eb96 }}/todo-application:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'listo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_349630b44a8545f8b77f75e8441302de }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9e56ad5a80334d628a223732ef98eb96 }}/todo-application:${{ github.sha }}'